### PR TITLE
merge LM and changes in fully-neural-lvsr

### PR DESCRIPTION
**Pull request by janchorowski**
subject

### CODE REVIEW

**Comment by rizar** [comment]
Hmm, can you please rebase? Merging merge commits is sort of  not nice....

**Comment by dmitriy-serdyuk** [comment]
I was always wondering why isn't it nice? Except that it adds a 'Merge...' commit.

**Comment by rizar** [comment]
Quick googling gave me lots of length discussions.. I just find the merge-less log a way neater, and since it is de-facto standard for Theano, Blocks, Fuel, let's follow it.

**Comment by janchorowski** [comment]
There you go.

**Pull request merged**
